apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  selector:
    matchLabels:
      app: k8s-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: k8s-devops-project
    spec:
      containers:
      - name: k8s-devops-project
        image: dvccloud/simple-devops-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
